[project]
name = "deploy"
queries = "./db/"

[local.dev]
port = 6969
build_mode = "release"
vector_config = { m = 64, ef_construction = 256, ef_search = 768 }
db_max_size_gb = 10
mcp = true
bm25 = true
embedding_model = "local"
graphvis_node_label = ""

[cloud]
